[package]
name = "example-collect-ts"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
specta = { workspace = true, features = ["derive", "collect"] }
specta-macros = { workspace = true, features = ["serde"] }
specta-typescript.workspace = true
specta-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
