//! Shared export pipeline infrastructure for all language exporters.
//!
//! This module provides the language-agnostic scaffolding that every exporter crate
//! plugs into: module graph construction, filesystem layout, path resolution,
//! file writing, stale file cleanup, and index/barrel file generation.
//!
//! Individual exporters implement [`ExportLanguage`] to provide language-specific
//! behavior (file extension, import syntax, type rendering). The pipeline handles
//! everything structural.

pub mod filesystem;
pub mod layout;
pub mod module_graph;
pub mod path_resolver;
pub mod pipeline;
pub mod topo_sort;

pub use layout::{
    FolderGrouping, ImportStyle, IndexFileConfig, Layout, MultiFileConfig, SingleFileConfig,
};
pub use module_graph::{Module, build_module_graph};
pub use path_resolver::{PathResolver, module_alias, relative_import_path};
pub use topo_sort::topological_sort_types;

use std::{
    borrow::Cow,
    collections::{BTreeMap, BTreeSet, HashMap},
    panic::Location,
};

use crate::{NamedConstant, Types, datatype::NamedDataType};

/// Result of rendering a module's types.
pub struct ModuleRenderResult {
    /// The rendered type declarations as a string.
    pub body: String,
    /// Map of exported type names to their source locations (for duplicate detection).
    pub exports: HashMap<String, Location<'static>>,
    /// Set of module paths that this module's types reference.
    /// Maps module_path -> import information including type names and value flags.
    pub referenced_modules: BTreeMap<String, ImportInfo>,
}

/// Information about what is imported from a specific module.
pub struct ImportInfo {
    /// The specific type names imported from this module.
    pub type_names: BTreeSet<String>,
    /// Whether any imported item is a runtime value (not just a type).
    /// Relevant for TypeScript `import` vs `import type` distinction.
    pub has_values: bool,
}

impl ImportInfo {
    /// Create a new empty ImportInfo.
    pub fn new() -> Self {
        Self {
            type_names: BTreeSet::new(),
            has_values: false,
        }
    }

    /// Merge another ImportInfo into this one.
    pub fn merge(&mut self, other: &ImportInfo) {
        self.type_names.extend(other.type_names.iter().cloned());
        self.has_values = self.has_values || other.has_values;
    }
}

impl Default for ImportInfo {
    fn default() -> Self {
        Self::new()
    }
}

/// An entry in an index/barrel file.
pub struct IndexFileEntry<'a> {
    /// File stem (without extension), e.g., `"item"` for `item.ts`.
    pub file_stem: &'a str,
    /// Names exported by this file.
    pub exported_names: &'a [String],
    /// The module path this file corresponds to.
    pub module_path: &'a str,
}

/// Trait implemented by language exporters to plug into the shared export pipeline.
///
/// The pipeline handles structural concerns (module graph, file layout, path resolution,
/// stale cleanup). The trait provides language-specific behavior (rendering, import syntax,
/// file extensions).
pub trait ExportLanguage {
    /// The exporter's error type.
    type Error: From<std::io::Error>;

    /// File extension for generated files, without the dot (e.g., `"ts"`, `"json"`, `"swift"`).
    fn file_extension(&self) -> &str;

    /// Extensions to match when scanning for stale generated files.
    /// Defaults to `[self.file_extension()]`. Override to include multiple
    /// (e.g., `["ts", "js"]` for TypeScript with JSDoc).
    fn stale_file_extensions(&self) -> Vec<&str> {
        vec![self.file_extension()]
    }

    /// Name of the index/barrel file in each directory (without extension).
    /// Return `None` to disable index file generation entirely.
    /// Examples: `Some("index")` for TS, `Some("mod")` for Rust, `None` for JSON Schema.
    fn index_file_stem(&self) -> Option<&str>;

    /// The string marker used to identify generated files for stale cleanup.
    /// Defaults to `"generated by Specta"`.
    fn generated_marker(&self) -> &str {
        "generated by Specta"
    }

    /// Render the file header (comments, preludes, framework imports).
    /// Called once per generated file.
    fn render_file_header(&self) -> String;

    /// Render the body for a single module's types.
    ///
    /// `types` is the full type collection (for reference lookups).
    /// `module_types` are the types belonging to this specific module, pre-sorted.
    /// `indent` is the indentation prefix (used for namespace nesting).
    ///
    /// Returns the rendered string and a set of referenced module paths
    /// that this module's types depend on.
    fn render_module_types(
        &self,
        types: &Types,
        module_types: &[&NamedDataType],
        indent: &str,
    ) -> Result<ModuleRenderResult, Self::Error>;

    /// Render import/reference statements for cross-module dependencies.
    ///
    /// `from_module_path` is the Rust module path of the file being rendered.
    /// `imports` maps target module paths to their import information (type names, value flags).
    /// `path_resolver` can resolve any module path to its relative filesystem path.
    ///
    /// Return the import block as a string (may be empty if the language doesn't
    /// use imports, e.g., JSON Schema uses `$ref` inline instead).
    fn render_imports(
        &self,
        from_module_path: &str,
        imports: &BTreeMap<String, ImportInfo>,
        path_resolver: &PathResolver,
    ) -> Result<String, Self::Error>;

    /// Render the contents of an index/barrel file for a directory.
    ///
    /// `files` lists the (file_stem, exported_names) pairs for each file in the directory.
    /// `subdirectories` lists subdirectory names that have their own index files.
    /// `path_resolver` resolves relative paths.
    ///
    /// Only called if `index_file_stem()` returns `Some(...)`.
    fn render_index_file(
        &self,
        _files: &[IndexFileEntry],
        _subdirectories: &[&str],
        _path_resolver: &PathResolver,
    ) -> Result<String, Self::Error> {
        Ok(String::new())
    }

    /// Render constants belonging to a module. Default: no-op.
    fn render_constants(&self, _constants: &[&NamedConstant]) -> Result<String, Self::Error> {
        Ok(String::new())
    }

    /// Compute the exported name for a type given the current layout.
    /// Default: uses module-prefixed name for `ModulePrefixedName` layout,
    /// bare name otherwise.
    fn exported_type_name(&self, layout: &Layout, ndt: &NamedDataType) -> Cow<'static, str> {
        match layout {
            Layout::SingleFile(config) if config.module_prefix_names => {
                let mut s = ndt.module_path().split("::").collect::<Vec<_>>().join("_");
                if !s.is_empty() {
                    s.push('_');
                }
                s.push_str(ndt.name());
                Cow::Owned(s)
            }
            _ => ndt.name().clone(),
        }
    }
}
