[package]
name = "specta"
description = "Easily export your Rust types to other languages"
version = "2.0.0-rc.24"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2024"
license = "MIT"
include = ["/src", "/examples", "/build.rs", "/LICENCE", "/README.md"]
repository = "https://github.com/specta-rs/specta"
documentation = "https://docs.rs/specta/latest/specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]
readme = "../README.md"

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Run `node ./.github/features.js` to update the docs
[features]
default = ["std"]

#! Core Features
## Enable support for the Rust standard library. Enabled by default.
std = []

## Derive macros
derive = ["dep:specta-macros"]

## Support for collecting up a global type map
collect = ["dep:ctor", "specta-macros/DO_NOT_USE_collect"]

## Companion enum generation for structs and enums
companion = ["specta-macros?/companion"]

#! Features
## Support for exporting the types of Rust functions.
function = ["specta-macros?/DO_NOT_USE_function", "dep:paste"]

#! Compatibility
## Support for [serde-json](https://github.com/serde-rs/json)
serde_json = ["dep:serde_json"]
## Support for [serde_yaml](https://github.com/dtolnay/serde-yaml)
serde_yaml = ["dep:serde_yaml"]
## Support for [toml](https://github.com/toml-rs/toml)
toml = ["dep:toml", "std"]

#! External types
## [uuid](https://docs.rs/uuid) crate
uuid = ["dep:uuid"]
## [uuid](https://docs.rs/ulid) crate
ulid = ["dep:ulid"]
## [chrono](https://docs.rs/chrono) crate
chrono = ["dep:chrono"]
## [time](https://docs.rs/time) crate
time = ["dep:time"]
# [jiff](https://docs.rs/jiff) crate
jiff = ["dep:jiff"]
## [bigdecimal](https://docs.rs/bigdecimal) crate
bigdecimal = ["dep:bigdecimal"]
## [rust_decimal](https://docs.rs/rust_decimal) crate
rust_decimal = ["dep:rust_decimal"]
## [indexmap](https://docs.rs/indexmap) crate
indexmap = ["dep:indexmap"]
## [ordered-float](https://docs.rs/ordered-float) crate
ordered-float = ["dep:ordered-float"]
## [heapless](https://docs.rs/heapless) crate
heapless = ["dep:heapless"]
## [semver](https://docs.rs/semver) crate
semver = ["dep:semver"]
## [smol_str](https://docs.rs/smol_str) crate
smol_str = ["dep:smol_str"]
## [arrayvec](https://docs.rs/arrayvec) crate
arrayvec = ["dep:arrayvec"]
## [smallvec](https://docs.rs/smallvec) crate
smallvec = ["dep:smallvec"]
## [ipnetwork](https://docs.rs/ipnetwork) crate
ipnetwork = ["dep:ipnetwork"]
## [mac_address](https://docs.rs/mac_address) crate
mac_address = ["dep:mac_address"]
## [bit-vec](https://docs.rs/bit-vec) crate
bit-vec = ["dep:bit-vec"]
## [bson](https://docs.rs/bson) crate
bson = ["dep:bson"]
## [bytes](https://docs.rs/bytes) crate
bytes = ["dep:bytes"]
## [uhlc](https://docs.rs/uhlc) crate
uhlc = ["dep:uhlc"]
## [bytesize](https://docs.rs/bytesize) crate
bytesize = ["dep:bytesize"]
## [glam](https://docs.rs/glam) crate
glam = ["dep:glam"]
## [tokio](https://docs.rs/tokio) crate
tokio = ["dep:tokio"]
## [url](https://docs.rs/url) crate
url = ["dep:url"]
## [either](https://docs.rs/either) crate
either = ["dep:either"]
## [error-stack](https://docs.rs/error-stack) crate
error-stack = ["dep:error-stack"]
# [bevy_ecs](https://docs.rs/bevy_ecs) crate
bevy_ecs = ["dep:bevy_ecs"]
# [bevy_input](https://docs.rs/bevy_input) crate
bevy_input = ["dep:bevy_input", "dep:bevy_ecs", "dep:glam"]
# [camino](https://docs.rs/camino) crate
camino = ["dep:camino"]
## [geojson](https://docs.rs/geojson) crate
geojson = ["dep:geojson", "serde_json"]
# [geozero](https://docs.rs/geozero) crate
geozero = ["dep:geozero"]

[lints]
workspace = true

[dependencies]
specta-macros = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
ctor = { workspace = true, optional = true }

# TODO: To be deprecated
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
ulid = { workspace = true, optional = true }
uuid = { workspace = true, optional = true } # TODO: Downgraded for Bevy (argh)
chrono = { workspace = true, optional = true }
time = { workspace = true, optional = true }
bigdecimal = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }     # TODO: Don't require `std`
ordered-float = { workspace = true, optional = true }
heapless = { workspace = true, optional = true }
semver = { workspace = true, optional = true }
smol_str = { workspace = true, optional = true }
arrayvec = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
ipnetwork = { workspace = true, optional = true }
mac_address = { workspace = true, optional = true }
bit-vec = { workspace = true, optional = true }
bson = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
uhlc = { workspace = true, optional = true }
bytesize = { workspace = true, optional = true }
glam = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
url = { workspace = true, optional = true }
either = { workspace = true, optional = true }
error-stack = { workspace = true, optional = true }
bevy_ecs = { workspace = true, optional = true }
bevy_input = { workspace = true, optional = true }
jiff = { workspace = true, optional = true }
camino = { workspace = true, optional = true }
geojson = { workspace = true, optional = true }
geozero = { workspace = true, optional = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] } # TODO: Can we remove this?

[build-dependencies]
rustc_version.workspace = true
