import { z } from "zod";
// This file has been generated by Specta. Do not edit this file manually.

import * as ex_shared from "./ex_shared";
export const AppConfigSchema = z.object({
	app_name: z.string(),
	debug: z.boolean(),
});
export type AppConfig = z.infer<typeof AppConfigSchema>;

export const CreateUserRequestSchema = z.object({
	name: z.string(),
	email: z.string(),
	role: ex_shared.RoleSchema,
	permission: ex_shared.PermissionSchema,
});
export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const UserListResponseSchema = z.object({
	users: z.array(ex_shared.UserSchema),
	pagination: ex_shared.PaginationSchema,
});
export type UserListResponse = z.infer<typeof UserListResponseSchema>;
