import { z } from "zod";
// This file has been generated by Specta. Do not edit this file manually.

import * as ex_shared from "./ex_shared";
export const AdjacentlyTaggedSchema = z.union([z.object({
	t: z.literal("unit_variant"),
}), z.object({
	t: z.literal("with_data"),
	c: z.string(),
}), z.object({
	t: z.literal("with_struct"),
	c: z.object({
	x: z.int(),
	y: z.int(),
}),
})]);

export const AppConfigSchema = z.object({
	app_name: z.string(),
	debug: z.boolean(),
});

export const CreateUserRequestSchema = z.object({
	name: z.string(),
	email: z.string(),
	role: ex_shared.RoleSchema,
	permission: ex_shared.PermissionSchema,
});

export const UserListResponseSchema = z.object({
	users: z.array(ex_shared.UserSchema),
	pagination: ex_shared.PaginationSchema,
});
