import { z } from "zod";
// This file has been generated by Specta. Do not edit this file manually.
export const PaginationSchema = z.object({
	page: z.int(),
	per_page: z.int(),
	total: z.int(),
});
export type Pagination = z.infer<typeof PaginationSchema>;

export const PermissionSchema = z.enum(["read_all", "write_all"]);
export type Permission = z.infer<typeof PermissionSchema>;

export const RoleSchema = z.enum(["Admin", "Guest", "Member"]);
export type Role = z.infer<typeof RoleSchema>;

export const UserIdSchema = z.int();
export type UserId = z.infer<typeof UserIdSchema>;

export const UserSchema = z.object({
	id: UserIdSchema,
	name: z.string(),
	email: z.string(),
	role: RoleSchema,
});
export type User = z.infer<typeof UserSchema>;
