import { z } from "zod";
// This file has been generated by Specta. Do not edit this file manually.
export const PaginationSchema = z.object({
	page: z.int(),
	per_page: z.int(),
	total: z.int(),
});

export const PermissionSchema = z.enum(["read_all", "write_all"]);

export const RoleSchema = z.enum(["Admin", "Guest", "Member"]);

export const UserIdSchema = z.int();

export const UserSchema = z.object({
	id: UserIdSchema,
	name: z.string(),
	email: z.string(),
	role: RoleSchema,
});
