// This file has been generated by Specta. Do not edit this file manually.

import * as ex_shared from "./ex_shared";
export type AdjacentlyTagged = { t: "unit_variant" } | { t: "with_data"; c: string } | { t: "with_struct"; c: {
	x: number,
	y: number,
} };

export type AppConfig = {
	app_name: string,
	debug: boolean,
};

export type CreateUserRequest = {
	name: string,
	email: string,
	role: ex_shared.Role,
	permission: ex_shared.Permission,
};

export type UserListResponse = {
	users: ex_shared.User[],
	pagination: ex_shared.Pagination,
};

export const CRATE_NAME = "app" as const;
