// This file has been generated by Specta. Do not edit this file manually.
export type Pagination = {
	page: number,
	per_page: number,
	total: number,
};

export enum Permission {
	read_all = "read_all",
}

export type Role = "Admin" | "Member" | "Guest";

export type User = {
	id: UserId,
	name: string,
	email: string,
	role: Role,
};

export type UserId = number;

export const CRATE_NAME = "shared" as const;
