use std::{
    borrow::Cow,
    collections::{BTreeMap, HashMap, HashSet},
    fmt,
    ops::Deref,
    panic::Location,
    path::{Path, PathBuf},
    sync::Arc,
};

use specta::{
    Constants, NamedConstant, ResolvedTypes, Types,
    datatype::{DataType, NamedDataType, Reference},
    export::{
        self, ExportLanguage, ImportInfo, IndexFileEntry, Layout, ModuleRenderResult, PathResolver,
        module_graph::Module,
    },
};

use crate::{Branded, Error, constants as const_export, primitives, references};

#[derive(Clone)]
#[allow(clippy::type_complexity)]
struct RuntimeFn(Arc<dyn Fn(FrameworkExporter) -> Result<Cow<'static, str>, Error> + Send + Sync>);

impl fmt::Debug for RuntimeFn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RuntimeFn({:p})", self.0)
    }
}

#[derive(Clone)]
#[allow(clippy::type_complexity)]
pub struct BrandedTypeImpl(
    pub(crate)  Arc<
        dyn for<'a> Fn(BrandedTypeExporter<'a>, &Branded) -> Result<Cow<'static, str>, Error>
            + Send
            + Sync,
    >,
);

impl fmt::Debug for BrandedTypeImpl {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "BrandedTypeImpl({:p})", self.0)
    }
}

/// Typescript language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Exporter {
    /// Custom header prepended to exported files.
    pub header: Cow<'static, str>,
    framework_runtime: Option<RuntimeFn>,
    pub(crate) branded_type_impl: Option<BrandedTypeImpl>,
    framework_prelude: Cow<'static, str>,
    /// Output layout mode for generated TypeScript.
    pub layout: Layout,
    /// When `true`, wrap output in TypeScript namespaces (single-file layouts only).
    pub(crate) use_namespaces: bool,
    pub(crate) jsdoc: bool,
    /// When `true`, bigint types (`i64`, `u64`, `i128`, `u128`, `isize`, `usize`, `f128`)
    /// are exported as `number` instead of returning an error.
    pub(crate) always_use_number: bool,
}

impl Exporter {
    // You should get this from either a [Typescript] or [JSDoc], not construct it directly.
    pub(crate) fn default() -> Exporter {
        Exporter {
            header: Cow::Borrowed(""),
            framework_runtime: None,
            branded_type_impl: None,
            framework_prelude: Cow::Borrowed(
                "// This file has been generated by Specta. Do not edit this file manually.",
            ),
            layout: Default::default(),
            use_namespaces: false,
            jsdoc: false,
            always_use_number: false,
        }
    }

    /// Provide a prelude which is added to the start of all exported files.
    pub fn framework_prelude(mut self, prelude: impl Into<Cow<'static, str>>) -> Self {
        self.framework_prelude = prelude.into();
        self
    }

    /// Add some custom Typescript or Javascript code that is exported as part of the bindings.
    /// It's appending to the types file for single-file layouts or put in a root `index.{ts/js}` for multi-file.
    ///
    /// The closure is wrapped in [`specta::collect()`] to capture any referenced types.
    /// Ensure you call `T::reference()` within the closure if you want an import to be created.
    pub fn framework_runtime(
        mut self,
        builder: impl Fn(FrameworkExporter) -> Result<Cow<'static, str>, Error> + Send + Sync + 'static,
    ) -> Self {
        self.framework_runtime = Some(RuntimeFn(Arc::new(builder)));
        self
    }

    /// Configure how `specta_typescript::branded!` types are rendered with exporter context.
    ///
    /// This callback receives both the branded payload and a [`BrandedTypeExporter`], allowing
    /// you to call [`BrandedTypeExporter::inline`] / [`BrandedTypeExporter::reference`] while
    /// preserving the current export configuration.
    ///
    /// # Examples
    ///
    /// `ts-brand` style:
    /// ```rust
    /// # use std::borrow::Cow;
    /// # use specta_typescript::{Branded, Error, Typescript};
    /// let exporter = Typescript::default().branded_type_impl(|ctx, branded| {
    ///     let datatype = ctx.inline(branded.ty())?;
    ///
    ///     Ok(Cow::Owned(format!(
    ///         "import(\"ts-brand\").Brand<{}, \"{}\">",
    ///         datatype,
    ///         branded.brand()
    ///     )))
    /// });
    /// # let _ = exporter;
    /// ```
    ///
    /// Effect style:
    /// ```rust
    /// # use std::borrow::Cow;
    /// # use specta_typescript::{Branded, Error, Typescript};
    /// let exporter = Typescript::default().branded_type_impl(|ctx, branded| {
    ///     let datatype = ctx.inline(branded.ty())?;
    ///
    ///     Ok(Cow::Owned(format!(
    ///         "{} & import(\"effect\").Brand.Brand<\"{}\">",
    ///         datatype,
    ///         branded.brand()
    ///     )))
    /// });
    /// # let _ = exporter;
    /// ```
    pub fn branded_type_impl(
        mut self,
        builder: impl for<'a> Fn(BrandedTypeExporter<'a>, &Branded) -> Result<Cow<'static, str>, Error>
        + Send
        + Sync
        + 'static,
    ) -> Self {
        self.branded_type_impl = Some(BrandedTypeImpl(Arc::new(builder)));
        self
    }

    /// Configure a header for the file.
    ///
    /// This is perfect for configuring lint ignore rules or other file-level comments.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Configure the bindings layout
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Export bigint types (`i64`, `u64`, `i128`, `u128`, `isize`, `usize`, `f128`) as `number`
    /// instead of returning an error.
    pub fn always_use_number(mut self, enable: bool) -> Self {
        self.always_use_number = enable;
        self
    }

    /// Enable TypeScript namespace wrapping for single-file output.
    ///
    /// When enabled, types are grouped into `namespace` blocks matching their
    /// Rust module paths. Only applies to `Layout::SingleFile` layouts.
    pub fn namespaces(mut self, enable: bool) -> Self {
        self.use_namespaces = enable;
        self
    }

    /// Export the files into a single string.
    ///
    /// Note: This returns an error if the layout is `Layout::MultiFile`.
    pub fn export(&self, resolved_types: &ResolvedTypes) -> Result<String, Error> {
        let types = resolved_types.as_types();

        if matches!(self.layout, Layout::MultiFile(_)) {
            return Err(Error::unable_to_export(&self.layout));
        }
        if self.use_namespaces && self.jsdoc {
            return Err(Error::unable_to_export_msg(
                "Namespaces with JSDoc is not supported",
            ));
        }

        let mut out = render_file_header(self)?;

        let mut has_manually_exported_user_types = false;
        let mut runtime = Ok(Cow::default());
        if let Some(framework_runtime) = &self.framework_runtime {
            runtime = (framework_runtime.0)(FrameworkExporter {
                exporter: self,
                has_manually_exported_user_types: &mut has_manually_exported_user_types,
                files_root_types: "",
                types: resolved_types,
            });
        }
        let runtime = runtime?;

        // Framework runtime
        if !runtime.is_empty() {
            out += "\n";
        }
        out += &runtime;
        if !runtime.is_empty() {
            out += "\n";
        }

        // User types (if not included in framework runtime)
        if !has_manually_exported_user_types {
            render_types(&mut out, self, types, "")?;
        }

        // Constants
        let constants = resolved_types.constants();
        if !constants.is_empty() {
            out.push('\n');
            const_export::export_constants_internal(&mut out, self, constants)?;
        }

        Ok(out)
    }

    /// Export the types to a specific file/folder.
    ///
    /// When configured when `format` is `Format::Files`, you must provide a directory path.
    /// Otherwise, you must provide the path of a single file.
    ///
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        resolved_types: &ResolvedTypes,
    ) -> Result<(), Error> {
        let types = resolved_types.as_types();
        let path = path.as_ref();

        if !matches!(self.layout, Layout::MultiFile(_)) {
            let result = self.export(resolved_types)?;
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            };
            std::fs::write(path, result)?;
            return Ok(());
        }

        // Build PathResolver for correct file placement and import path resolution
        let path_resolver = export::PathResolver::new(
            self.file_extension(),
            self.index_file_stem(),
            &self.layout,
            types,
            resolved_types.constants(),
        );

        fn export_module(
            exporter: &Exporter,
            types: &Types,
            module: &mut Module,
            s: &mut String,
            all_exports: &mut HashMap<String, Location<'static>>,
            root_path: &Path,
            files: &mut HashMap<PathBuf, String>,
            file_info: &mut HashMap<PathBuf, FileExportInfo>,
            path_resolver: &PathResolver,
        ) -> Result<bool, Error> {
            module.types.sort_by(|a, b| {
                a.name()
                    .cmp(b.name())
                    .then(a.module_path().cmp(b.module_path()))
                    .then(a.location().cmp(&b.location()))
            });
            let (rendered_types_result, referenced_types) =
                references::with_module_path(module.module_path.as_ref(), || {
                    references::collect_references(|| {
                        let mut rendered = String::new();
                        let exports = render_flat_types(
                            &mut rendered,
                            exporter,
                            types,
                            module.types.iter().copied(),
                            "",
                        )?;
                        Ok::<_, Error>((rendered, exports))
                    })
                });
            let (rendered_types, exports) = rendered_types_result?;

            // Build ImportInfo map with type names (needed for Named import style)
            let import_info: BTreeMap<String, ImportInfo> = referenced_types
                .into_iter()
                .filter_map(|r| {
                    r.get(types).map(|ndt| {
                        let is_value = matches!(
                            ndt.ty(),
                            DataType::Enum(e) if crate::legacy::is_native_ts_enum(e)
                        );
                        (
                            ndt.module_path().as_ref().to_string(),
                            ndt.name().to_string(),
                            is_value,
                        )
                    })
                })
                .filter(|(module_path, _, _)| module_path != module.module_path.as_ref())
                .fold(BTreeMap::new(), |mut acc, (path, type_name, is_value)| {
                    let entry = acc.entry(path).or_insert_with(ImportInfo::new);
                    entry.type_names.insert(type_name);
                    entry.has_values = entry.has_values || is_value;
                    acc
                });

            if !import_info.is_empty() {
                s.push('\n');
                s.push_str(&module_import_block(
                    exporter,
                    module.module_path.as_ref(),
                    &import_info,
                    path_resolver,
                ));
            }

            if !import_info.is_empty() && !rendered_types.is_empty() {
                s.push('\n');
            }

            s.push_str(&rendered_types);

            // Constants belonging to this module
            if !module.constants.is_empty() {
                module.constants.sort_by(|a, b| a.name.cmp(&b.name));
                if !rendered_types.is_empty() {
                    s.push('\n');
                }
                for constant in &module.constants {
                    const_export::export_constant_internal(s, exporter, constant)?;
                }
            }

            let has_content = !exports.is_empty() || !module.constants.is_empty();
            all_exports.extend(exports);

            for (_name, child_module) in &mut module.children {
                if child_module.types.is_empty()
                    && child_module.constants.is_empty()
                    && child_module.children.is_empty()
                {
                    continue;
                }

                let mut out = render_file_header(exporter)?;
                let mut child_exports = HashMap::new();

                let has_types = export_module(
                    exporter,
                    types,
                    child_module,
                    &mut out,
                    &mut child_exports,
                    root_path,
                    files,
                    file_info,
                    path_resolver,
                )?;
                if has_types {
                    // Use PathResolver for correct file placement (respects FolderGrouping)
                    let file_path = path_resolver
                        .module_file_path(child_module.module_path.as_ref())
                        .map(|rel| root_path.join(rel))
                        .unwrap_or_else(|| {
                            let mut p = root_path.join(child_module.module_path.replace("::", "/"));
                            p.set_extension(exporter.file_extension());
                            p
                        });

                    file_info.insert(
                        file_path.clone(),
                        FileExportInfo {
                            exported_names: child_exports.keys().cloned().collect(),
                            module_path: child_module.module_path.to_string(),
                        },
                    );
                    files.insert(file_path, out);
                }
            }

            Ok(has_content)
        }

        let mut files = HashMap::new();
        let mut file_info: HashMap<PathBuf, FileExportInfo> = HashMap::new();
        let mut runtime_path = path.join("index");
        runtime_path.set_extension(if self.jsdoc { "js" } else { "ts" });

        let mut root_types = String::new();
        let mut root_exports = HashMap::new();
        let mut module_graph = export::build_module_graph(types, resolved_types.constants());
        // Extract root constants before passing to export_module(); they go into index.ts
        let root_constants: Vec<_> = std::mem::take(&mut module_graph.constants);
        export_module(
            self,
            types,
            &mut module_graph,
            &mut root_types,
            &mut root_exports,
            path,
            &mut files,
            &mut file_info,
            &path_resolver,
        )?;

        {
            let mut has_manually_exported_user_types = false;
            let mut runtime = Cow::default();
            let mut runtime_references = HashSet::new();
            if let Some(framework_runtime) = &self.framework_runtime {
                let (runtime_result, referenced_types) = references::with_module_path("", || {
                    references::collect_references(|| {
                        (framework_runtime.0)(FrameworkExporter {
                            exporter: self,
                            has_manually_exported_user_types: &mut has_manually_exported_user_types,
                            files_root_types: &root_types,
                            types: resolved_types,
                        })
                    })
                });
                runtime = runtime_result?;
                runtime_references = referenced_types;
            }

            let should_export_user_types =
                !has_manually_exported_user_types && !root_types.is_empty();
            let has_constants = !root_constants.is_empty();

            if !runtime.is_empty() || should_export_user_types || has_constants {
                files.insert(runtime_path.clone(), {
                    let mut out = render_file_header(self)?;
                    let mut body = String::new();

                    // Framework runtime
                    if !runtime.is_empty() {
                        body.push_str(&runtime);
                    }

                    // User types (if not included in framework runtime)
                    if should_export_user_types {
                        if !body.is_empty() {
                            body.push('\n');
                        }

                        body.push_str(&root_types);
                    }

                    // Build import info for runtime references
                    let import_info: BTreeMap<String, ImportInfo> = runtime_references
                        .into_iter()
                        .filter_map(|r| {
                            r.get(types).map(|ndt| {
                                let is_value = matches!(
                                    ndt.ty(),
                                    DataType::Enum(e) if crate::legacy::is_native_ts_enum(e)
                                );
                                (
                                    ndt.module_path().as_ref().to_string(),
                                    ndt.name().to_string(),
                                    is_value,
                                )
                            })
                        })
                        .filter(|(module_path, _, _)| !module_path.is_empty())
                        .fold(BTreeMap::new(), |mut acc, (path, type_name, is_value)| {
                            let entry = acc.entry(path).or_insert_with(ImportInfo::new);
                            entry.type_names.insert(type_name);
                            entry.has_values = entry.has_values || is_value;
                            acc
                        });

                    if !import_info.is_empty() {
                        out.push('\n');
                        out.push_str(&module_import_block(self, "", &import_info, &path_resolver));
                    }

                    if !body.is_empty() {
                        out.push('\n');
                        if !import_info.is_empty() {
                            out.push('\n');
                        }
                        out.push_str(&body);
                    }

                    // Root-level constants (no module path)
                    if has_constants {
                        out.push('\n');
                        for constant in &root_constants {
                            const_export::export_constant_internal(&mut out, self, constant)?;
                        }
                    }

                    out
                });
            }
        }

        // Generate index files if configured
        if let Layout::MultiFile(config) = &self.layout {
            if let export::IndexFileConfig::ReExportAll = &config.index_files {
                generate_index_files(self, path, &file_info, &mut files, &path_resolver)?;
            }
        }

        match path.metadata() {
            Ok(meta) if !meta.is_dir() => std::fs::remove_file(path).or_else(|source| {
                if source.kind() == std::io::ErrorKind::NotFound {
                    Ok(())
                } else {
                    Err(Error::remove_file(path.to_path_buf(), source))
                }
            })?,
            Ok(_) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::metadata(path.to_path_buf(), source));
            }
        }

        for (path, content) in &files {
            path.parent().map(std::fs::create_dir_all).transpose()?;
            std::fs::write(path, content)?;
        }

        // Use shared filesystem cleanup
        let extensions = self.stale_file_extensions();
        let ext_refs: Vec<&str> = extensions.iter().map(|s| *s).collect();
        export::filesystem::cleanup_stale_files(path, &files, &ext_refs, self.generated_marker())?;

        Ok(())
    }
}

// --- ExportLanguage trait implementation ---

impl ExportLanguage for Exporter {
    type Error = Error;

    fn file_extension(&self) -> &str {
        if self.jsdoc { "js" } else { "ts" }
    }

    fn stale_file_extensions(&self) -> Vec<&str> {
        vec!["ts", "js"]
    }

    fn index_file_stem(&self) -> Option<&str> {
        Some("index")
    }

    fn render_file_header(&self) -> String {
        render_file_header(self).unwrap_or_default()
    }

    fn render_module_types(
        &self,
        types: &Types,
        module_types: &[&NamedDataType],
        indent: &str,
    ) -> Result<ModuleRenderResult, Error> {
        // Infer the module path from the types being rendered
        let module_path = module_types
            .first()
            .map(|ndt| ndt.module_path().as_ref().to_string())
            .unwrap_or_default();

        let (result, referenced_types) = references::with_module_path(&module_path, || {
            references::collect_references(|| {
                let mut rendered = String::new();
                let exports = render_flat_types(
                    &mut rendered,
                    self,
                    types,
                    module_types.iter().copied(),
                    indent,
                )?;
                Ok::<_, Error>((rendered, exports))
            })
        });
        let (body, exports) = result?;

        let mut referenced_modules: BTreeMap<String, ImportInfo> = BTreeMap::new();
        for r in referenced_types {
            if let Some(ndt) = r.get(types) {
                let mod_path = ndt.module_path().as_ref().to_string();
                let type_name = ndt.name().to_string();
                let is_value = matches!(
                    ndt.ty(),
                    DataType::Enum(e) if crate::legacy::is_native_ts_enum(e)
                );
                let entry = referenced_modules
                    .entry(mod_path)
                    .or_insert_with(ImportInfo::new);
                entry.type_names.insert(type_name);
                entry.has_values = entry.has_values || is_value;
            }
        }

        Ok(ModuleRenderResult {
            body,
            exports,
            referenced_modules,
        })
    }

    fn render_imports(
        &self,
        from_module_path: &str,
        imports: &BTreeMap<String, ImportInfo>,
        path_resolver: &PathResolver,
    ) -> Result<String, Error> {
        Ok(module_import_block(
            self,
            from_module_path,
            imports,
            path_resolver,
        ))
    }

    fn render_index_file(
        &self,
        files: &[IndexFileEntry],
        subdirectories: &[&str],
        _path_resolver: &PathResolver,
    ) -> Result<String, Error> {
        let mut out = String::new();

        // Re-export from each file
        for entry in files {
            out.push_str("export * from \"./");
            out.push_str(entry.file_stem);
            out.push_str("\";\n");
        }

        // Re-export from subdirectories
        for subdir in subdirectories {
            out.push_str("export * from \"./");
            out.push_str(subdir);
            out.push_str("\";\n");
        }

        Ok(out)
    }

    fn render_constants(&self, constants: &[&NamedConstant]) -> Result<String, Error> {
        let mut s = String::new();
        for constant in constants {
            const_export::export_constant_internal(&mut s, self, constant)?;
        }
        Ok(s)
    }

    fn exported_type_name(&self, layout: &Layout, ndt: &NamedDataType) -> Cow<'static, str> {
        match layout {
            Layout::SingleFile(config) if config.module_prefix_names => {
                let mut s = ndt.module_path().split("::").collect::<Vec<_>>().join("_");
                s.push('_');
                s.push_str(ndt.name());
                Cow::Owned(s)
            }
            _ => ndt.name().clone(),
        }
    }
}

impl AsRef<Exporter> for Exporter {
    fn as_ref(&self) -> &Exporter {
        self
    }
}

impl AsMut<Exporter> for Exporter {
    fn as_mut(&mut self) -> &mut Exporter {
        self
    }
}

/// Reference to Typescript language exporter for branded type callbacks.
pub struct BrandedTypeExporter<'a> {
    pub(crate) exporter: &'a Exporter,
    /// Collected types currently being exported.
    pub types: &'a ResolvedTypes,
}

impl fmt::Debug for BrandedTypeExporter<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.exporter.fmt(f)
    }
}

impl AsRef<Exporter> for BrandedTypeExporter<'_> {
    fn as_ref(&self) -> &Exporter {
        self
    }
}

impl Deref for BrandedTypeExporter<'_> {
    type Target = Exporter;

    fn deref(&self) -> &Self::Target {
        self.exporter
    }
}

impl BrandedTypeExporter<'_> {
    /// [primitives::inline]
    pub fn inline(&self, dt: &DataType) -> Result<String, Error> {
        primitives::inline(self, self.types, dt)
    }

    /// [primitives::reference]
    pub fn reference(&self, r: &Reference) -> Result<String, Error> {
        primitives::reference(self, self.types, r)
    }
}

/// Reference to Typescript language exporter for framework
pub struct FrameworkExporter<'a> {
    exporter: &'a Exporter,
    has_manually_exported_user_types: &'a mut bool,
    // For `Layout::Files` we need to inject the value
    files_root_types: &'a str,
    /// Collected types currently being exported.
    pub types: &'a ResolvedTypes,
}

impl fmt::Debug for FrameworkExporter<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.exporter.fmt(f)
    }
}

impl AsRef<Exporter> for FrameworkExporter<'_> {
    fn as_ref(&self) -> &Exporter {
        self
    }
}

impl Deref for FrameworkExporter<'_> {
    type Target = Exporter;

    fn deref(&self) -> &Self::Target {
        self.exporter
    }
}

impl FrameworkExporter<'_> {
    /// Render the types within the [`ResolvedTypes`](specta::ResolvedTypes).
    ///
    /// This will only work if used within [`Exporter::framework_runtime`].
    /// It allows frameworks to intersperse their user types into their runtime code.
    pub fn render_types(&mut self) -> Result<Cow<'static, str>, Error> {
        let mut s = String::new();
        render_types(
            &mut s,
            self.exporter,
            self.types.as_types(),
            self.files_root_types,
        )?;
        *self.has_manually_exported_user_types = true;
        Ok(Cow::Owned(s))
    }

    /// [primitives::inline]
    pub fn inline(&self, dt: &DataType) -> Result<String, Error> {
        primitives::inline(self, self.types, dt)
    }

    /// [primitives::reference]
    pub fn reference(&self, r: &Reference) -> Result<String, Error> {
        primitives::reference(self, self.types, r)
    }

    /// [primitives::export]
    pub fn export<'a>(
        &self,
        ndts: impl Iterator<Item = &'a NamedDataType>,
        indent: &'a str,
    ) -> Result<String, Error> {
        primitives::export(self, self.types, ndts, indent)
    }
}

fn render_file_header(exporter: &Exporter) -> Result<String, Error> {
    let mut out = exporter.header.to_string();
    if !exporter.header.is_empty() {
        out += "\n";
    }

    out += &exporter.framework_prelude;
    if !exporter.framework_prelude.is_empty() {
        out += "\n";
    }

    Ok(out)
}

fn render_types(
    s: &mut String,
    exporter: &Exporter,
    types: &Types,
    files_user_types: &str,
) -> Result<(), Error> {
    if exporter.use_namespaces && matches!(exporter.layout, Layout::SingleFile(_)) {
        fn has_renderable_content(module: &Module<'_>, types: &Types) -> bool {
            module.types.iter().any(|ndt| ndt.requires_reference(types))
                || module
                    .children
                    .values()
                    .any(|child| has_renderable_content(child, types))
        }

        fn export_ns<'a>(
            exporter: &Exporter,
            types: &Types,
            s: &mut String,
            module: impl ExactSizeIterator<Item = (&'a &'a str, &'a mut Module<'a>)>,
            depth: usize,
        ) -> Result<(), Error> {
            let namespace_indent = "\t".repeat(depth);
            let content_indent = "\t".repeat(depth + 1);

            for (name, module) in module {
                if !has_renderable_content(module, types) {
                    continue;
                }

                s.push('\n');
                s.push_str(&namespace_indent);
                if depth != 0 && *name != "$specta$" {
                    s.push_str("export ");
                }
                s.push_str("namespace ");
                s.push_str(name);
                s.push_str(" {\n");

                // Types
                module.types.sort_by(|a, b| {
                    a.name()
                        .cmp(b.name())
                        .then(a.module_path().cmp(b.module_path()))
                        .then(a.location().cmp(&b.location()))
                });
                render_flat_types(
                    s,
                    exporter,
                    types,
                    module.types.iter().copied(),
                    &content_indent,
                )?;

                // Namespaces
                export_ns(exporter, types, s, module.children.iter_mut(), depth + 1)?;

                s.push_str(&namespace_indent);
                s.push_str("}\n");
            }

            Ok(())
        }

        let empty_constants = Constants::default();
        let mut module = export::build_module_graph(types, &empty_constants);

        let reexports = {
            let mut reexports = String::new();
            for name in module
                .children
                .iter()
                .filter_map(|(name, module)| has_renderable_content(module, types).then_some(*name))
                .chain(
                    module
                        .types
                        .iter()
                        .filter(|ndt| ndt.requires_reference(types))
                        .map(|ndt| ndt.name().as_ref()),
                )
            {
                reexports.push_str("export import ");
                reexports.push_str(name);
                reexports.push_str(" = $s$.");
                reexports.push_str(name);
                reexports.push_str(";\n");
            }
            reexports
        };

        export_ns(exporter, types, s, [(&"$s$", &mut module)].into_iter(), 0)?;
        s.push_str(&reexports);
    } else {
        match &exporter.layout {
            Layout::SingleFile(_) => {
                render_flat_types(s, exporter, types, types.into_sorted_iter(), "")?;
            }
            // The types will get their own files
            // So we keep the user types empty for easy downstream detection.
            Layout::MultiFile(_) => {
                if !files_user_types.is_empty() {
                    s.push_str(files_user_types);
                }
            }
        }
    }

    Ok(())
}

// Implementation of `Layout::ModulePrefixedName | Layout::FlatFile`,
// but is used by `Layout::Namespace` and `Layout::Files`
fn render_flat_types<'a>(
    s: &mut String,
    exporter: &Exporter,
    types: &Types,
    ndts: impl ExactSizeIterator<Item = &'a NamedDataType>,
    indent: &str,
) -> Result<HashMap<String, Location<'static>>, Error> {
    let mut exports = HashMap::with_capacity(ndts.len());

    let ndts = ndts
        .filter(|ndt| ndt.requires_reference(types))
        .map(|ndt| {
            let export_name = exported_type_name(exporter, ndt);
            if let Some(other) = exports.insert(export_name.to_string(), ndt.location()) {
                return Err(Error::duplicate_type_name(
                    export_name,
                    ndt.location(),
                    other,
                ));
            }

            Ok(ndt)
        })
        .collect::<Result<Vec<_>, _>>()?;

    primitives::export_internal(s, exporter, types, ndts.into_iter(), indent)?;

    Ok(exports)
}

fn exported_type_name(exporter: &Exporter, ndt: &NamedDataType) -> Cow<'static, str> {
    match &exporter.layout {
        Layout::SingleFile(config) if config.module_prefix_names => {
            let mut s = ndt.module_path().split("::").collect::<Vec<_>>().join("_");
            s.push('_');
            s.push_str(ndt.name());
            Cow::Owned(s)
        }
        _ => ndt.name().clone(),
    }
}

/// Compute the module alias for namespace imports.
/// Now delegates to the shared implementation.
pub(crate) fn module_alias(module_path: &str) -> String {
    export::module_alias(module_path)
}

fn module_import_block(
    exporter: &Exporter,
    from_module_path: &str,
    imports: &BTreeMap<String, ImportInfo>,
    path_resolver: &PathResolver,
) -> String {
    if exporter.jsdoc {
        let mut out = String::from("/**\n");

        for module_path in imports.keys() {
            out.push_str(" * @typedef {import(\"");
            out.push_str(&path_resolver.relative_import_path(from_module_path, module_path));
            out.push_str("\")} ");
            out.push_str(&export::module_alias(module_path));
            out.push('\n');
        }

        out.push_str(" */");
        out
    } else {
        let import_style = match &exporter.layout {
            Layout::MultiFile(config) => &config.import_style,
            _ => &export::ImportStyle::Namespace,
        };

        imports
            .iter()
            .map(|(module_path, info)| {
                let import_keyword = if exporter.jsdoc || info.has_values {
                    "import"
                } else {
                    "import type"
                };
                let rel_path = path_resolver.relative_import_path(from_module_path, module_path);

                match import_style {
                    export::ImportStyle::Named => {
                        let names: Vec<_> = info.type_names.iter().cloned().collect();
                        format!(
                            "{} {{ {} }} from \"{}\";",
                            import_keyword,
                            names.join(", "),
                            rel_path
                        )
                    }
                    export::ImportStyle::Namespace => {
                        format!(
                            "{} * as {} from \"{}\";",
                            import_keyword,
                            export::module_alias(module_path),
                            rel_path
                        )
                    }
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Information about exported types in a generated file, used for index file generation.
struct FileExportInfo {
    exported_names: Vec<String>,
    module_path: String,
}

/// Generate index/barrel files for directories containing generated files.
fn generate_index_files(
    exporter: &Exporter,
    _root: &Path,
    file_info: &HashMap<PathBuf, FileExportInfo>,
    files: &mut HashMap<PathBuf, String>,
    path_resolver: &PathResolver,
) -> Result<(), Error> {
    // Group files by parent directory
    let mut dirs: BTreeMap<PathBuf, Vec<(&PathBuf, &FileExportInfo)>> = BTreeMap::new();
    for (path, info) in file_info {
        if let Some(parent) = path.parent() {
            dirs.entry(parent.to_path_buf())
                .or_default()
                .push((path, info));
        }
    }

    let index_stem = match exporter.index_file_stem() {
        Some(stem) => stem,
        None => return Ok(()),
    };

    for (dir, dir_files) in &dirs {
        let entries: Vec<IndexFileEntry> = dir_files
            .iter()
            .filter_map(|(path, info)| {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .filter(|stem| *stem != index_stem)
                    .map(|stem| IndexFileEntry {
                        file_stem: stem,
                        exported_names: &info.exported_names,
                        module_path: &info.module_path,
                    })
            })
            .collect();

        // Find subdirectories that have their own index files
        let subdirs: Vec<&str> = dirs
            .keys()
            .filter(|other_dir| other_dir.parent() == Some(dir) && *other_dir != dir)
            .filter_map(|d| d.file_name().and_then(|n| n.to_str()))
            .collect();

        if !entries.is_empty() || !subdirs.is_empty() {
            let mut index_path = dir.join(index_stem);
            index_path.set_extension(exporter.file_extension());

            let rendered = exporter.render_index_file(&entries, &subdirs, path_resolver)?;
            if rendered.is_empty() {
                continue;
            }

            // Append re-exports to existing index file, or create a new one
            if let Some(existing) = files.get_mut(&index_path) {
                if !existing.is_empty() {
                    existing.push('\n');
                }
                existing.push_str(&rendered);
            } else {
                let mut out = render_file_header(exporter)?;
                if !out.is_empty() {
                    out.push('\n');
                }
                out.push_str(&rendered);
                files.insert(index_path, out);
            }
        }
    }

    Ok(())
}
