use std::{borrow::Cow, path::Path};

use specta::ResolvedTypes;

use crate::{
    Error, Exporter, Layout,
    exporter::{BigIntExportBehavior, ExportMode, ZodConfig, ZodVersion},
};

// Layout is re-exported from specta::export via crate::Layout

/// Zod schema exporter.
///
/// Produces Zod schema declarations (`export const XSchema = z.object({...})`)
/// instead of TypeScript type declarations. Output files are `.ts`.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Zod(Exporter);

impl Default for Zod {
    fn default() -> Self {
        Self::new()
    }
}

impl From<Zod> for Exporter {
    fn from(value: Zod) -> Self {
        value.0
    }
}

impl From<Exporter> for Zod {
    fn from(mut value: Exporter) -> Self {
        value.mode = ExportMode::Zod(ZodConfig::default());
        Self(value)
    }
}

impl Zod {
    /// Construct a new Zod exporter with default options configured.
    pub fn new() -> Self {
        let mut exporter = Exporter::default().framework_prelude(
            "import { z } from \"zod\";\n// This file has been generated by Specta. Do not edit this file manually.",
        );
        exporter.mode = ExportMode::Zod(ZodConfig::default());
        Self(exporter)
    }

    /// Construct a Zod v3 exporter.
    pub fn v3() -> Self {
        Self::new().zod_version(ZodVersion::V3)
    }

    /// Configure a header for the file.
    ///
    /// This is perfect for configuring lint ignore rules or other file-level comments.
    pub fn header(self, header: impl Into<Cow<'static, str>>) -> Self {
        Self(self.0.header(header))
    }

    /// Configure the layout of the generated file.
    pub fn layout(self, layout: Layout) -> Self {
        Self(self.0.layout(layout))
    }

    /// Configure BigInt handling behaviour.
    pub fn bigint(mut self, bigint: BigIntExportBehavior) -> Self {
        if let ExportMode::Zod(c) = &mut self.0.mode {
            c.bigint = bigint;
        }
        self
    }

    /// Configure the target Zod version.
    pub fn zod_version(mut self, version: ZodVersion) -> Self {
        if let ExportMode::Zod(c) = &mut self.0.mode {
            c.zod_version = version;
        }
        self
    }

    /// Configure whether to export inferred TypeScript types (`export type X = z.infer<...>`).
    pub fn output_type_infers(mut self, export: bool) -> Self {
        if let ExportMode::Zod(c) = &mut self.0.mode {
            c.output_type_infers = export;
        }
        self
    }

    /// Provide a prelude which is added to the start of all exported files.
    pub fn framework_prelude(self, prelude: impl Into<Cow<'static, str>>) -> Self {
        Self(self.0.framework_prelude(prelude))
    }

    /// Add runtime code exported as part of the bindings.
    pub fn framework_runtime(
        self,
        builder: impl Fn(crate::FrameworkExporter<'_>) -> Result<Cow<'static, str>, Error>
        + Send
        + Sync
        + 'static,
    ) -> Self {
        Self(self.0.framework_runtime(builder))
    }

    /// Export the files into a single string.
    ///
    /// Note: This returns an error if the layout is `Layout::MultiFile`.
    pub fn export(&self, types: &ResolvedTypes) -> Result<String, Error> {
        self.0.export(types)
    }

    /// Export the types to a specific file/folder.
    ///
    /// When configured with `Layout::MultiFile`, you must provide a directory path.
    /// Otherwise, you must provide the path of a single file.
    pub fn export_to(&self, path: impl AsRef<Path>, types: &ResolvedTypes) -> Result<(), Error> {
        self.0.export_to(path, types)
    }
}

impl AsRef<Exporter> for Zod {
    fn as_ref(&self) -> &Exporter {
        &self.0
    }
}

impl AsMut<Exporter> for Zod {
    fn as_mut(&mut self) -> &mut Exporter {
        &mut self.0
    }
}
