use std::{
    borrow::Cow,
    collections::{BTreeMap, HashMap, HashSet},
    fmt,
    ops::Deref,
    path::{Path, PathBuf},
    sync::Arc,
};

use specta::{
    ResolvedTypes, Types,
    datatype::{DataType, NamedDataType, Reference},
    export::{
        self, ExportLanguage, ImportInfo, IndexFileEntry, Layout, ModuleRenderResult, PathResolver,
        module_graph::Module, topo_sort::topological_sort_types,
    },
};

use crate::{Error, primitives, references};

/// Target Zod version for generated schemas.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum ZodVersion {
    /// Zod v3 — stable, backward-compatible output
    V3,
    /// Zod v4 — uses `z.strictObject()`, `z.int()`, and other v4-specific APIs.
    #[default]
    V4,
}

/// Allows configuring how Specta's Zod exporter will deal with BigInt types ([i64], [i128] etc).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum BigIntExportBehavior {
    /// Export BigInt as a Zod string schema.
    String,
    /// Export BigInt as a Zod number schema.
    Number,
    /// Export BigInt as a Zod bigint schema.
    BigInt,
    /// Abort export on BigInt usage.
    #[default]
    Fail,
}

#[derive(Clone)]
#[allow(clippy::type_complexity)]
struct RuntimeFn(
    Arc<dyn Fn(FrameworkExporter<'_>) -> Result<Cow<'static, str>, Error> + Send + Sync>,
);

impl fmt::Debug for RuntimeFn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RuntimeFn({:p})", self.0)
    }
}

/// Zod language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Zod {
    /// Custom header prepended to exported files.
    pub header: Cow<'static, str>,
    framework_runtime: Option<RuntimeFn>,
    framework_prelude: Cow<'static, str>,
    /// Strategy for exporting Rust bigint-compatible primitives.
    pub bigint: BigIntExportBehavior,
    /// Output layout mode for generated Zod TypeScript.
    pub layout: Layout,
    /// Target Zod version for generated schemas.
    pub zod_version: ZodVersion,
    /// Whether to export inferred TypeScript types (`export type X = z.infer<...>`).
    pub output_type_infers: bool,
}

impl Default for Zod {
    fn default() -> Self {
        Self::new()
    }
}

impl Zod {
    /// Construct a new exporter with default options configured.
    pub fn new() -> Self {
        Self {
            header: Cow::Borrowed(""),
            framework_runtime: None,
            framework_prelude: Cow::Borrowed(
                "import { z } from \"zod\";\n// This file has been generated by Specta. Do not edit this file manually.",
            ),
            bigint: Default::default(),
            layout: Default::default(),
            zod_version: Default::default(),
            output_type_infers: true,
        }
    }

    pub fn v3() -> Self {
        Self::new().zod_version(ZodVersion::V3)
    }

    /// Provide a prelude which is added to the start of all exported files.
    pub fn framework_prelude(mut self, prelude: impl Into<Cow<'static, str>>) -> Self {
        self.framework_prelude = prelude.into();
        self
    }

    /// Add runtime code exported as part of the bindings.
    pub fn framework_runtime(
        mut self,
        builder: impl Fn(FrameworkExporter<'_>) -> Result<Cow<'static, str>, Error>
        + Send
        + Sync
        + 'static,
    ) -> Self {
        self.framework_runtime = Some(RuntimeFn(Arc::new(builder)));
        self
    }

    /// Configure a header for the file.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Configure BigInt handling behaviour.
    pub fn bigint(mut self, bigint: BigIntExportBehavior) -> Self {
        self.bigint = bigint;
        self
    }

    /// Configure bindings layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Configure the target Zod version.
    pub fn zod_version(mut self, version: ZodVersion) -> Self {
        self.zod_version = version;
        self
    }

    /// Configure whether to export inferred TypeScript types (`export type X = z.infer<...>`).
    pub fn output_type_infers(mut self, export: bool) -> Self {
        self.output_type_infers = export;
        self
    }

    /// Export files into a single string.
    pub fn export(&self, resolved_types: &ResolvedTypes) -> Result<String, Error> {
        let types = resolved_types.as_types();

        if matches!(self.layout, Layout::MultiFile(_)) {
            return Err(Error::unable_to_export(&self.layout));
        }

        let mut out = render_file_header(self);

        let mut has_manually_exported_user_types = false;
        let mut runtime = Ok(Cow::default());
        if let Some(framework_runtime) = &self.framework_runtime {
            runtime = (framework_runtime.0)(FrameworkExporter {
                exporter: self,
                has_manually_exported_user_types: &mut has_manually_exported_user_types,
                files_root_types: "",
                types: resolved_types,
            });
        }
        let runtime = runtime?;

        if !runtime.is_empty() {
            out.push('\n');
            out.push_str(&runtime);
            out.push('\n');
        }

        if !has_manually_exported_user_types {
            render_types(&mut out, self, types, "")?;
        }

        Ok(out)
    }

    /// Export the types to a specific file/folder.
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        resolved_types: &ResolvedTypes,
    ) -> Result<(), Error> {
        let types = resolved_types.as_types();
        let path = path.as_ref();

        if !matches!(self.layout, Layout::MultiFile(_)) {
            let result = self.export(resolved_types)?;
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, result)?;
            return Ok(());
        }

        // Build PathResolver for correct file placement and import path resolution
        let path_resolver = export::PathResolver::new(
            self.file_extension(),
            self.index_file_stem(),
            &self.layout,
            types,
            resolved_types.constants(),
        );

        fn export_module(
            exporter: &Zod,
            types: &Types,
            module: &mut Module,
            s: &mut String,
            all_exports: &mut HashMap<String, std::panic::Location<'static>>,
            root_path: &Path,
            files: &mut HashMap<PathBuf, String>,
            file_info: &mut HashMap<PathBuf, FileExportInfo>,
            path_resolver: &PathResolver,
        ) -> Result<bool, Error> {
            module.types.sort_by(|a, b| {
                a.name()
                    .cmp(b.name())
                    .then(a.module_path().cmp(b.module_path()))
                    .then(a.location().cmp(&b.location()))
            });

            let (rendered_types_result, referenced_types) =
                references::with_module_path(module.module_path.as_ref(), || {
                    references::collect_references(|| {
                        let mut rendered = String::new();
                        let exports = render_flat_types(
                            &mut rendered,
                            exporter,
                            types,
                            module.types.iter().copied(),
                            "",
                        )?;
                        Ok::<_, Error>((rendered, exports))
                    })
                });

            let (rendered_types, exports) = rendered_types_result?;

            // Build ImportInfo map with type names (needed for Named import style)
            let import_info: BTreeMap<String, ImportInfo> = referenced_types
                .into_iter()
                .filter_map(|r| {
                    r.get(types).map(|ndt| {
                        (
                            ndt.module_path().as_ref().to_string(),
                            ndt.name().to_string(),
                        )
                    })
                })
                .filter(|(module_path, _)| module_path != module.module_path.as_ref())
                .fold(BTreeMap::new(), |mut acc, (path, type_name)| {
                    let entry = acc.entry(path).or_insert_with(ImportInfo::new);
                    entry.type_names.insert(type_name);
                    acc
                });

            if !import_info.is_empty() {
                s.push('\n');
                s.push_str(&module_import_block(
                    exporter,
                    module.module_path.as_ref(),
                    &import_info,
                    path_resolver,
                ));
            }

            if !import_info.is_empty() && !rendered_types.is_empty() {
                s.push('\n');
            }

            s.push_str(&rendered_types);

            let has_content = !exports.is_empty();
            all_exports.extend(exports);

            for (_name, child_module) in &mut module.children {
                if child_module.types.is_empty() && child_module.children.is_empty() {
                    continue;
                }

                let mut out = render_file_header(exporter);
                let mut child_exports = HashMap::new();

                let has_types = export_module(
                    exporter,
                    types,
                    child_module,
                    &mut out,
                    &mut child_exports,
                    root_path,
                    files,
                    file_info,
                    path_resolver,
                )?;
                if has_types {
                    // Use PathResolver for correct file placement (respects FolderGrouping)
                    let file_path = path_resolver
                        .module_file_path(child_module.module_path.as_ref())
                        .map(|rel| root_path.join(rel))
                        .unwrap_or_else(|| {
                            let mut p = root_path.join(child_module.module_path.replace("::", "/"));
                            p.set_extension(exporter.file_extension());
                            p
                        });

                    file_info.insert(
                        file_path.clone(),
                        FileExportInfo {
                            exported_names: child_exports.keys().cloned().collect(),
                            module_path: child_module.module_path.to_string(),
                        },
                    );
                    files.insert(file_path, out);
                }
            }

            Ok(has_content)
        }

        let mut files = HashMap::new();
        let mut file_info: HashMap<PathBuf, FileExportInfo> = HashMap::new();
        let mut runtime_path = path.join("index");
        runtime_path.set_extension("ts");

        let mut root_types = String::new();
        let mut root_exports = HashMap::new();
        let empty_constants = specta::Constants::default();
        export_module(
            self,
            types,
            &mut export::build_module_graph(types, &empty_constants),
            &mut root_types,
            &mut root_exports,
            path,
            &mut files,
            &mut file_info,
            &path_resolver,
        )?;

        {
            let mut has_manually_exported_user_types = false;
            let mut runtime = Cow::default();
            let mut runtime_references = HashSet::new();
            if let Some(framework_runtime) = &self.framework_runtime {
                let (runtime_result, referenced_types) = references::with_module_path("", || {
                    references::collect_references(|| {
                        (framework_runtime.0)(FrameworkExporter {
                            exporter: self,
                            has_manually_exported_user_types: &mut has_manually_exported_user_types,
                            files_root_types: &root_types,
                            types: resolved_types,
                        })
                    })
                });
                runtime = runtime_result?;
                runtime_references = referenced_types;
            }

            let should_export_user_types =
                !has_manually_exported_user_types && !root_types.is_empty();

            if !runtime.is_empty() || should_export_user_types {
                files.insert(runtime_path.clone(), {
                    let mut out = render_file_header(self);
                    let mut body = String::new();

                    if !runtime.is_empty() {
                        body.push_str(&runtime);
                    }

                    if should_export_user_types {
                        if !body.is_empty() {
                            body.push('\n');
                        }
                        body.push_str(&root_types);
                    }

                    // Build import info for runtime references
                    let import_info: BTreeMap<String, ImportInfo> = runtime_references
                        .into_iter()
                        .filter_map(|r| {
                            r.get(types).map(|ndt| {
                                (
                                    ndt.module_path().as_ref().to_string(),
                                    ndt.name().to_string(),
                                )
                            })
                        })
                        .filter(|(module_path, _)| !module_path.is_empty())
                        .fold(BTreeMap::new(), |mut acc, (path, type_name)| {
                            let entry = acc.entry(path).or_insert_with(ImportInfo::new);
                            entry.type_names.insert(type_name);
                            acc
                        });

                    if !import_info.is_empty() {
                        out.push('\n');
                        out.push_str(&module_import_block(self, "", &import_info, &path_resolver));
                    }

                    if !body.is_empty() {
                        out.push('\n');
                        if !import_info.is_empty() {
                            out.push('\n');
                        }
                        out.push_str(&body);
                    }

                    out
                });
            }
        }

        // Generate index files if configured
        if let Layout::MultiFile(config) = &self.layout {
            if let export::IndexFileConfig::ReExportAll = &config.index_files {
                generate_index_files(self, path, &file_info, &mut files, &path_resolver)?;
            }
        }

        match path.metadata() {
            Ok(meta) if !meta.is_dir() => std::fs::remove_file(path).or_else(|source| {
                if source.kind() == std::io::ErrorKind::NotFound {
                    Ok(())
                } else {
                    Err(Error::remove_file(path.to_path_buf(), source))
                }
            })?,
            Ok(_) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::metadata(path.to_path_buf(), source));
            }
        }

        for (path, content) in &files {
            path.parent().map(std::fs::create_dir_all).transpose()?;
            std::fs::write(path, content)?;
        }

        // Use shared filesystem cleanup
        let extensions = self.stale_file_extensions();
        let ext_refs: Vec<&str> = extensions.iter().map(|s| *s).collect();
        export::filesystem::cleanup_stale_files(path, &files, &ext_refs, self.generated_marker())?;

        Ok(())
    }
}

// --- ExportLanguage trait implementation ---

impl ExportLanguage for Zod {
    type Error = Error;

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn stale_file_extensions(&self) -> Vec<&str> {
        vec!["ts"]
    }

    fn index_file_stem(&self) -> Option<&str> {
        Some("index")
    }

    fn render_file_header(&self) -> String {
        render_file_header(self)
    }

    fn render_module_types(
        &self,
        types: &Types,
        module_types: &[&NamedDataType],
        indent: &str,
    ) -> Result<ModuleRenderResult, Error> {
        // Infer the module path from the types being rendered
        let module_path = module_types
            .first()
            .map(|ndt| ndt.module_path().as_ref().to_string())
            .unwrap_or_default();

        let (result, referenced_types) = references::with_module_path(&module_path, || {
            references::collect_references(|| {
                let mut rendered = String::new();
                let exports = render_flat_types(
                    &mut rendered,
                    self,
                    types,
                    module_types.iter().copied(),
                    indent,
                )?;
                Ok::<_, Error>((rendered, exports))
            })
        });
        let (body, exports) = result?;

        let mut referenced_modules: BTreeMap<String, ImportInfo> = BTreeMap::new();
        for r in referenced_types {
            if let Some(ndt) = r.get(types) {
                let mod_path = ndt.module_path().as_ref().to_string();
                let type_name = ndt.name().to_string();
                let entry = referenced_modules
                    .entry(mod_path)
                    .or_insert_with(ImportInfo::new);
                entry.type_names.insert(type_name);
                // Zod schemas are always runtime values, but has_values
                // is only relevant for TS import/import type distinction
            }
        }

        Ok(ModuleRenderResult {
            body,
            exports,
            referenced_modules,
        })
    }

    fn render_imports(
        &self,
        from_module_path: &str,
        imports: &BTreeMap<String, ImportInfo>,
        path_resolver: &PathResolver,
    ) -> Result<String, Error> {
        Ok(module_import_block(
            self,
            from_module_path,
            imports,
            path_resolver,
        ))
    }

    fn render_index_file(
        &self,
        files: &[IndexFileEntry],
        subdirectories: &[&str],
        _path_resolver: &PathResolver,
    ) -> Result<String, Error> {
        let mut out = String::new();

        // Re-export from each file
        for entry in files {
            out.push_str("export * from \"./");
            out.push_str(entry.file_stem);
            out.push_str("\";\n");
        }

        // Re-export from subdirectories
        for subdir in subdirectories {
            out.push_str("export * from \"./");
            out.push_str(subdir);
            out.push_str("\";\n");
        }

        Ok(out)
    }

    fn exported_type_name(&self, layout: &Layout, ndt: &NamedDataType) -> Cow<'static, str> {
        match layout {
            Layout::SingleFile(config) if config.module_prefix_names => {
                let mut s = ndt.module_path().split("::").collect::<Vec<_>>().join("_");
                if !s.is_empty() {
                    s.push('_');
                }
                s.push_str(ndt.name());
                Cow::Owned(s)
            }
            _ => ndt.name().clone(),
        }
    }
}

impl AsRef<Zod> for Zod {
    fn as_ref(&self) -> &Zod {
        self
    }
}

impl AsMut<Zod> for Zod {
    fn as_mut(&mut self) -> &mut Zod {
        self
    }
}

/// Reference to the Zod exporter for framework callbacks.
pub struct FrameworkExporter<'a> {
    exporter: &'a Zod,
    has_manually_exported_user_types: &'a mut bool,
    files_root_types: &'a str,
    /// Collected types currently being exported.
    pub types: &'a ResolvedTypes,
}

impl fmt::Debug for FrameworkExporter<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.exporter.fmt(f)
    }
}

impl AsRef<Zod> for FrameworkExporter<'_> {
    fn as_ref(&self) -> &Zod {
        self.exporter
    }
}

impl Deref for FrameworkExporter<'_> {
    type Target = Zod;

    fn deref(&self) -> &Self::Target {
        self.exporter
    }
}

impl FrameworkExporter<'_> {
    /// Render the types within [`ResolvedTypes`](specta::ResolvedTypes).
    pub fn render_types(&mut self) -> Result<Cow<'static, str>, Error> {
        let mut s = String::new();
        render_types(
            &mut s,
            self.exporter,
            self.types.as_types(),
            self.files_root_types,
        )?;
        *self.has_manually_exported_user_types = true;
        Ok(Cow::Owned(s))
    }

    /// [primitives::inline]
    pub fn inline(&self, dt: &DataType) -> Result<String, Error> {
        primitives::inline(self, self.types, dt)
    }

    /// [primitives::reference]
    pub fn reference(&self, r: &Reference) -> Result<String, Error> {
        primitives::reference(self, self.types, r)
    }

    /// [primitives::export]
    pub fn export<'a>(
        &self,
        ndts: impl Iterator<Item = &'a NamedDataType>,
        indent: &'a str,
    ) -> Result<String, Error> {
        primitives::export(self, self.types, ndts, indent)
    }
}

fn render_file_header(exporter: &Zod) -> String {
    let mut out = exporter.header.to_string();
    if !exporter.header.is_empty() {
        out.push('\n');
    }

    out.push_str(&exporter.framework_prelude);
    if !exporter.framework_prelude.is_empty() {
        out.push('\n');
    }

    out
}

fn render_types(
    s: &mut String,
    exporter: &Zod,
    types: &Types,
    files_user_types: &str,
) -> Result<(), Error> {
    match &exporter.layout {
        Layout::SingleFile(_) => {
            render_flat_types(s, exporter, types, types.into_sorted_iter(), "")?;
        }
        Layout::MultiFile(_) => {
            if !files_user_types.is_empty() {
                s.push_str(files_user_types);
            }
        }
    }

    Ok(())
}

fn render_flat_types<'a>(
    s: &mut String,
    exporter: &Zod,
    types: &Types,
    ndts: impl ExactSizeIterator<Item = &'a NamedDataType>,
    indent: &str,
) -> Result<HashMap<String, std::panic::Location<'static>>, Error> {
    let mut exports = HashMap::with_capacity(ndts.len());

    let ndts = ndts
        .filter(|ndt| ndt.requires_reference(types))
        .map(|ndt| {
            let export_name = exported_type_name(exporter, ndt);
            if let Some(other) = exports.insert(export_name.to_string(), ndt.location()) {
                return Err(Error::duplicate_type_name(
                    export_name,
                    ndt.location(),
                    other,
                ));
            }
            Ok(ndt)
        })
        .collect::<Result<Vec<_>, _>>()?;

    // Use shared topological sort
    let ndts = topological_sort_types(ndts, types);

    primitives::export_internal(s, exporter, types, ndts.into_iter(), indent)?;

    Ok(exports)
}

fn exported_type_name(exporter: &Zod, ndt: &NamedDataType) -> Cow<'static, str> {
    match &exporter.layout {
        Layout::SingleFile(config) if config.module_prefix_names => {
            let mut s = ndt.module_path().split("::").collect::<Vec<_>>().join("_");
            if !s.is_empty() {
                s.push('_');
            }
            s.push_str(ndt.name());
            Cow::Owned(s)
        }
        _ => ndt.name().clone(),
    }
}

/// Compute the module alias for namespace imports.
/// Delegates to the shared implementation.
pub(crate) fn module_alias(module_path: &str) -> String {
    export::module_alias(module_path)
}

fn module_import_block(
    exporter: &Zod,
    from_module_path: &str,
    imports: &BTreeMap<String, ImportInfo>,
    path_resolver: &PathResolver,
) -> String {
    let import_style = match &exporter.layout {
        Layout::MultiFile(config) => &config.import_style,
        _ => &export::ImportStyle::Namespace,
    };

    imports
        .iter()
        .map(|(module_path, info)| {
            let rel_path = path_resolver.relative_import_path(from_module_path, module_path);

            match import_style {
                export::ImportStyle::Named => {
                    let names: Vec<_> = info.type_names.iter().cloned().collect();
                    format!("import {{ {} }} from \"{}\";", names.join(", "), rel_path)
                }
                export::ImportStyle::Namespace => {
                    format!(
                        "import * as {} from \"{}\";",
                        export::module_alias(module_path),
                        rel_path
                    )
                }
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Information about exported types in a generated file, used for index file generation.
struct FileExportInfo {
    exported_names: Vec<String>,
    module_path: String,
}

/// Generate index/barrel files for directories containing generated files.
fn generate_index_files(
    exporter: &Zod,
    _root: &Path,
    file_info: &HashMap<PathBuf, FileExportInfo>,
    files: &mut HashMap<PathBuf, String>,
    path_resolver: &PathResolver,
) -> Result<(), Error> {
    let mut dirs: BTreeMap<PathBuf, Vec<(&PathBuf, &FileExportInfo)>> = BTreeMap::new();
    for (path, info) in file_info {
        if let Some(parent) = path.parent() {
            dirs.entry(parent.to_path_buf())
                .or_default()
                .push((path, info));
        }
    }

    let index_stem = match exporter.index_file_stem() {
        Some(stem) => stem,
        None => return Ok(()),
    };

    for (dir, dir_files) in &dirs {
        let entries: Vec<IndexFileEntry> = dir_files
            .iter()
            .filter_map(|(path, info)| {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .filter(|stem| *stem != index_stem)
                    .map(|stem| IndexFileEntry {
                        file_stem: stem,
                        exported_names: &info.exported_names,
                        module_path: &info.module_path,
                    })
            })
            .collect();

        let subdirs: Vec<&str> = dirs
            .keys()
            .filter(|other_dir| other_dir.parent() == Some(dir) && *other_dir != dir)
            .filter_map(|d| d.file_name().and_then(|n| n.to_str()))
            .collect();

        if !entries.is_empty() || !subdirs.is_empty() {
            let mut index_path = dir.join(index_stem);
            index_path.set_extension(exporter.file_extension());

            let rendered = exporter.render_index_file(&entries, &subdirs, path_resolver)?;
            if rendered.is_empty() {
                continue;
            }

            // Append re-exports to existing index file, or create a new one
            if let Some(existing) = files.get_mut(&index_path) {
                if !existing.is_empty() {
                    existing.push('\n');
                }
                existing.push_str(&rendered);
            } else {
                let mut out = render_file_header(exporter);
                if !out.is_empty() {
                    out.push('\n');
                }
                out.push_str(&rendered);
                files.insert(index_path, out);
            }
        }
    }

    Ok(())
}
