[package]
name = "example-basic-ts"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
specta = { workspace = true, features = ["derive"] }
specta-typescript.workspace = true
specta-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
serde_repr.workspace = true
